web/app/controllers/application_controller.py
import csv
import glob
import json
import os
import sqlite3
from web.database.sqlite_util import createTable
from flask import redirect, Blueprint, request, render_template, send_file,url_for
from ast import literal_eval
from vad.VadModel import VadModel
from web.database.sqlite_util import getallVoiceRecord,deleteVoiceRecord
appc = Blueprint('application', __name__, url_prefix='/')

model = VadModel()


@appc.route('/')
def index():
    #查找当前数据库里面的所有语音记录
    data_list = getallVoiceRecord()
    progress_px = 780
    print(data_list)
    temp = []
    for item in data_list:
        #这里的section需要转换下，让前段不需要计算
        section_list = literal_eval(item[3])
        result = []
        last_end = 0
        for s_item in section_list:
            #每一个百分比乘以当前进度条的长度，当前进度条长度为200px
            if last_end==0:
                result.append([s_item[0]*progress_px,s_item[1]*progress_px,0])
            else:
                result.append([s_item[0]*progress_px,s_item[1]*progress_px,s_item[0]*progress_px-last_end])
            last_end = s_item[1]*progress_px
        print(result)
        temp.append({"id":item[0],"path":item[1],"voice_len":item[2],"section":result,"created_time":item[4]})
    kwargs = {"data": temp}
    return render_template("mainpage.html",**kwargs)

@appc.route('/delete/<id>',methods=['GET'])
def delete_voice(id):
    deleteVoiceRecord(id)
    #TODO 同时需要删除掉web/output里面的文件
    return {"code":200}


@appc.route('/voice_list')
def voice_list():
    progress_px =780
    data_list = getallVoiceRecord()
    print(data_list)
    temp = []
    for item in data_list:
        # 这里的section需要转换下，让前段不需要计算
        section_list = literal_eval(item[3])
        result = []
        last_end = 0
        for s_item in section_list:
            print(s_item)
            # 每一个百分比乘以当前进度条的长度
            # if last_end == 0:
            #     result.append({"width":"%.3fpx"%(s_item[1]* progress_px-s_item[0] * progress_px),"left":"0px"} )
            # else:
            result.append({"width":"%.3fpx"%(s_item[1] * progress_px-s_item[0] * progress_px),"left": "%.3fpx"%(s_item[0] * progress_px )})
            # last_end = s_item[1] * progress_px
        temp.append({"id": item[0], "path": item[1], "voice_len": item[2], "section": result, "created_time": item[4]})
    print(temp)
    return json.dumps(temp)

@appc.route('/upload')
def upload():
    return render_template("upload.html")
@appc.route('/uploader', methods=['GET', 'POST'])
def uploader():
    """
        文件上传
    """
    if request.method == 'POST':
        # input标签中的name的属性值
        f = request.files['file']
        # 拼接地址，上传地址，f.filename：直接获取文件名
        f.save(os.path.join(model.upload_folder, f.filename))
        # 输出上传的文件名
        print(request.files, f.filename)
        # 读取保存完成音频文件开始转换文件，然后返回文件
        model.start(f.filename)
        #重定向回首页
        return {"code":200,"result":"上传完成"}



@appc.route('/download/<filename>')
def download_file(filename):
    # 构造供下载文件的完整路径
    path = os.path.join(model.cur_path, "output/%s"%filename)
    return send_file(path, as_attachment=True)

web/templates/download.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>文件下载</title>

        <style>
            a{
                text-decoration: none;
                color: #2062e0;
            }
            a:hover{
                text-decoration: none;
                color: #2062e0;
            }
        </style>

    </head>
    <body>
        <div align="center">
            <h1>转换后的文件下载</h1><br><br>
            {# 将指定文件夹中的文件获取遍历显示 #}
            {% for n in name %}

            <a href="output/{{ n }}">{{ n }}</a>
            <a href={{ url_for('application.download_file', filename=n) }}>
            <button>下载</button>
            </a>
            <br>
            {% endfor %}
        </div>
    </body>
</html>

web/templates/upload.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>上传</title>
        <script src="https://libs.afengim.com/libs/jquery-3.1.1/jquery-3.1.1.min.js" type="application/javascript"></script>
        <style>下载文件
            a{
                text-decoration: none;
                color: #2062e0;
            }
            a:hover{
                text-decoration: none;
                color: #2062e0;
            }
            .loaderbg {
      background-color: #fff;
      width: 100%;
      height: 100%;
                display: none;
      overflow: hidden;
      position: fixed;
      left: 0;
      top: 0;
      z-index: 99999999
    }

    ::-webkit-scrollbar {
      width: 7.5px;
      height: 6px;
      background-color: #f0f0f0;
      display: none
    }

    ::-webkit-scrollbar-thumb {
      background-color: #b1b1b1;
      border-radius: 15px
    }

    ::-webkit-scrollbar-thumb:hover {
      background-color: #777
    }

    .spinner {
      position: absolute;
      top: 50%;
      left: 50%;
      margin-left: -25px;
      margin-top: -30px;
      width: 150px;
      height: 60px;
      text-align: center;
      font-size: 10px
    }

    .spinner > .double {
      background: #49a9ee;
      height: 100%;
      width: 6px;
      display: inline-block;
      -webkit-animation: stretchDelay 1.2s infinite ease-in-out;
      animation: stretchDelay 1.2s infinite ease-in-out
    }

    .spinner .rect2 {
      -webkit-animation-delay: -1.1s;
      animation-delay: -1.1s
    }

    .spinner .rect3 {
      -webkit-animation-delay: -1.0s;
      animation-delay: -1.0s
    }

    .spinner .rect4 {
      -webkit-animation-delay: -0.9s;
      animation-delay: -0.9s
    }

    .spinner .rect5 {
      -webkit-animation-delay: -0.8s;
      animation-delay: -0.8s
    }

    @-webkit-keyframes stretchDelay {

      0%,
      40%,
      100% {
        -webkit-transform: scaleY(.4)
      }

      20% {
        -webkit-transform: scaleY(1)
      }
    }

    @keyframes stretchDelay {

      0%,
      40%,
      100% {
        transform: scaleY(.4);
        -webkit-transform: scaleY(.4)
      }

      20% {
        transform: scaleY(1);
        -webkit-transform: scaleY(1)
      }
    }

        </style>
    </head>
    <body>
         <a id="item" href={{ url_for('application.index') }}>
                    <button id="add_voice">返回主页</button>
                </a>
        <h1 align="center">上传单个语音文件(格式最好是m4a,wav,mp3)</h1>
         <h1 align="center">提交按钮点击一次就好，不要重复提交，转换一次所需要的时间在1分钟-2分钟</h1>
        <div align="center">

            <form action="/uploader" method="post" enctype="multipart/form-data">
                <br><br><br>
                <input type="file" name="file" accept=".txt, .pdf, .doc, .docx, .md" value="{{ csrf_token }}" />
                <br><br><br>
                <input type="submit" value="提交" onclick="commit()" />
            </form>

            <br><br><br>
        </div>
        <div class="loaderbg">
          <div class="spinner">
            <div class="double rect1"></div>
            <div class="double rect2"></div>
            <div class="double rect3"></div>
            <div class="double rect4"></div>
            <div class="double rect5"></div>
            <h3>正在转换中,请等待...</h3>

        </div>
        </div>

    <script type="text/javascript">
  //页面加载完成之后隐藏loading
  $(window).load(function () {

  });
  //设置页面加载3秒之后隐藏loading
  function commit(){
       $(".loaderbg").show()
  }
  {#$(function () {#}
  {#  setTimeout(function () {#}
  {#    $(".loaderbg").hide();#}
  {#  }, 3000);#}
  {#    })#}

    </script>

    </body>
</html>